"""empty message

Revision ID: 614478e9c7e2
Revises: 
Create Date: 2018-09-08 19:30:38.295000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '614478e9c7e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('utilisateur',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=50), nullable=False),
    sa.Column('prenom', sa.String(length=50), nullable=False),
    sa.Column('date_de_naissance', sa.TIMESTAMP(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nom'),
    sa.UniqueConstraint('prenom')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('utilisateur')
    # ### end Alembic commands ###
